// This file is auto-generated by: npm run supabase:types
// Run that command after any schema changes to keep types in sync.
// Manual edits will be overwritten.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'employee' | 'manager' | 'hr_admin' | 'super_admin'

export type NominationStatus =
  | 'draft'
  | 'pending'
  | 'clarification_requested'
  | 'approved'
  | 'rejected'

export type RecognitionSource = 'peer' | 'manager' | 'hr' | 'leadership'

export type PeriodType = 'annual' | 'quarterly'

export type NotificationType =
  | 'nomination_submitted'
  | 'approval_required'
  | 'clarification_requested'
  | 'nomination_approved'
  | 'nomination_rejected'
  | 'recognition_received'
  | 'team_recognition_published'
  | 'badge_unlocked'
  | 'monthly_report_ready'

export interface Database {
  public: {
    Tables: {
      departments: {
        Row: {
          id: string
          name: string
          description: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['departments']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['departments']['Insert']>
      }
      employees: {
        Row: {
          id: string
          auth_user_id: string | null
          employee_id: string
          full_name: string
          email: string
          role: UserRole
          department_id: string | null
          manager_id: string | null
          avatar_url: string | null
          is_active: boolean
          joined_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['employees']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['employees']['Insert']>
      }
      projects: {
        Row: {
          id: string
          name: string
          description: string | null
          project_code: string | null
          manager_id: string | null
          is_active: boolean
          archived_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['projects']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['projects']['Insert']>
      }
      project_members: {
        Row: {
          id: string
          project_id: string
          employee_id: string
          joined_at: string
          left_at: string | null
          is_active: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['project_members']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['project_members']['Insert']>
      }
      core_values: {
        Row: {
          id: string
          name: string
          slug: string
          definition: string
          icon: string
          accent_color: string
          display_order: number
          is_active: boolean
          archived_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['core_values']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['core_values']['Insert']>
      }
      behaviours: {
        Row: {
          id: string
          core_value_id: string
          name: string
          description: string | null
          examples: string[] | null
          display_order: number
          is_active: boolean
          archived_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['behaviours']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['behaviours']['Insert']>
      }
      scenarios: {
        Row: {
          id: string
          behaviour_id: string
          core_value_id: string
          name: string
          description: string | null
          examples: string[] | null
          display_order: number
          is_active: boolean
          archived_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['scenarios']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['scenarios']['Insert']>
      }
      nominations: {
        Row: {
          id: string
          nominator_id: string
          nominee_id: string
          core_value_id: string
          behaviour_id: string | null
          scenario_id: string | null
          what_happened: string
          what_impact: string
          project_id: string | null
          snapshot_nominator_dept: string | null
          snapshot_nominee_dept: string | null
          snapshot_nominee_manager_id: string | null
          snapshot_core_value_name: string
          snapshot_behaviour_name: string | null
          snapshot_scenario_name: string | null
          snapshot_project_name: string | null
          recognition_source: RecognitionSource
          status: NominationStatus
          assigned_approver_id: string | null
          escalation_level: number
          approved_by_id: string | null
          approved_at: string | null
          rejected_by_id: string | null
          rejected_at: string | null
          rejection_reason: string | null
          clarification_requested_at: string | null
          clarification_note: string | null
          clarification_responded_at: string | null
          published_at: string | null
          idempotency_key: string | null
          submitted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['nominations']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['nominations']['Insert']>
      }
      nomination_appreciations: {
        Row: {
          id: string
          nomination_id: string
          employee_id: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['nomination_appreciations']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: never
      }
      badge_definitions: {
        Row: {
          id: string
          level: number
          name: string
          description: string
          minimum_count: number
          maximum_count: number | null
          icon: string
          accent_color: string
          display_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['badge_definitions']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['badge_definitions']['Insert']>
      }
      employee_value_badges: {
        Row: {
          id: string
          employee_id: string
          core_value_id: string
          period_type: PeriodType
          period_start: string
          period_end: string
          recognition_count: number
          unique_recognizer_count: number
          badge_level: number | null
          last_updated: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['employee_value_badges']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['employee_value_badges']['Insert']>
      }
      badge_history: {
        Row: {
          id: string
          employee_id: string
          core_value_id: string
          previous_level: number | null
          new_level: number
          recognition_count: number
          achieved_at: string
          period_type: PeriodType
          period_start: string
          period_end: string
        }
        Insert: Omit<Database['public']['Tables']['badge_history']['Row'], 'id'> & { id?: string }
        Update: never
      }
      notifications: {
        Row: {
          id: string
          recipient_id: string
          type: NotificationType
          title: string
          body: string
          related_id: string | null
          related_type: string | null
          is_read: boolean
          read_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
      }
      audit_logs: {
        Row: {
          id: string
          actor_id: string | null
          actor_email: string | null
          action: string
          entity_type: string
          entity_id: string | null
          previous_value: Json | null
          new_value: Json | null
          ip_address: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['audit_logs']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: never
      }
      app_config: {
        Row: {
          key: string
          value: Json
          description: string | null
          updated_by: string | null
          updated_at: string
        }
        Insert: Database['public']['Tables']['app_config']['Row']
        Update: Partial<Database['public']['Tables']['app_config']['Insert']>
      }
      rewards: {
        Row: {
          id: string
          name: string
          description: string | null
          frequency: string | null
          eligibility_criteria: string | null
          value_description: string | null
          requires_approval: boolean
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['rewards']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['rewards']['Insert']>
      }
      reward_assignments: {
        Row: {
          id: string
          reward_id: string
          employee_id: string
          assigned_by: string
          nomination_id: string | null
          notes: string | null
          assigned_at: string
        }
        Insert: Omit<Database['public']['Tables']['reward_assignments']['Row'], 'id'> & { id?: string }
        Update: never
      }
      reciprocal_recognition_flags: {
        Row: {
          id: string
          employee_a_id: string
          employee_b_id: string
          count: number
          last_flagged_at: string
          is_reviewed: boolean
          reviewed_by_id: string | null
          reviewed_at: string | null
          notes: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['reciprocal_recognition_flags']['Row'], 'id' | 'created_at'> & { id?: string }
        Update: Partial<Database['public']['Tables']['reciprocal_recognition_flags']['Insert']>
      }
    }
    Views: {
      v_recognition_feed: {
        Row: {
          id: string
          approved_at: string | null
          published_at: string | null
          what_happened: string
          what_impact: string
          recognition_source: RecognitionSource
          nominator_id: string
          nominator_name: string
          nominator_avatar: string | null
          nominee_id: string
          nominee_name: string
          nominee_avatar: string | null
          core_value_id: string
          core_value_name: string
          core_value_color: string
          core_value_icon: string
          behaviour_name: string | null
          scenario_name: string | null
          project_name: string | null
          project_id: string | null
          appreciation_count: number
        }
      }
    }
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
